/**
 * Open transport sources for Ukraine found by auditing the MobilityData Mobility Database catalog
 * (github.com/MobilityData/mobility-database-catalogs) and the GBFS systems list (github.com/MobilityData/gbfs),
 * then probing every URL (October 2026). Nothing here is invented: each entry has a catalogue reference.
 * `access` records what the audit found; sources that are not open are registered but never enabled.
 */
export interface CatalogEntry {
  name: string; city: string; providerType: 'public_transit' | 'scooter'; sourceType: 'gtfs' | 'gtfs_rt' | 'gbfs' | 'json';
  feedUrl: string; access: 'open' | 'requires_credentials' | 'insecure_endpoint'; license?: string; updateFrequency?: string; coverage: string; sourceRef: string; priority?: number;
}

const lvivLicense = 'Open data portal of Lviv city (opendata.city-adm.lviv.ua)';
export const ukraineCatalog: CatalogEntry[] = [
  { name: 'Львівавтодор — розклад (GTFS)', city: 'Львів', providerType: 'public_transit', sourceType: 'gtfs', feedUrl: 'https://track.ua-gis.com/gtfs/lviv/static.zip', access: 'open', license: lvivLicense, updateFrequency: 'періодично (статичний розклад)', coverage: 'Громадський транспорт Львова: автобуси, трамваї', sourceRef: 'mdb:ua-lviv-lvivavtodor-gtfs-2374', priority: 10 },
  { name: 'Львівавтодор — realtime позиції (GTFS-RT)', city: 'Львів', providerType: 'public_transit', sourceType: 'gtfs_rt', feedUrl: 'https://track.ua-gis.com/gtfs/lviv/vehicle_position', access: 'open', license: lvivLicense, updateFrequency: 'реальний час (секунди)', coverage: 'Позиції транспорту Львова', sourceRef: 'mdb:ua-lviv-lvivavtodor-gtfs-rt-vp-2376', priority: 10 },
  { name: 'Львівавтодор — затримки (GTFS-RT)', city: 'Львів', providerType: 'public_transit', sourceType: 'gtfs_rt', feedUrl: 'https://track.ua-gis.com/gtfs/lviv/trip_updates', access: 'open', license: lvivLicense, updateFrequency: 'реальний час', coverage: 'Оновлення рейсів і затримки Львова', sourceRef: 'mdb:ua-lviv-lvivavtodor-gtfs-rt-tu-2375', priority: 20 },
  { name: 'Стрийська міська рада — розклад (GTFS)', city: 'Стрий', providerType: 'public_transit', sourceType: 'gtfs', feedUrl: 'https://track.ua-gis.com/gtfs/stryi/static.zip', access: 'open', updateFrequency: 'періодично', coverage: 'Міський транспорт Стрия', sourceRef: 'mdb:ua-stryi-gtfs-2932', priority: 10 },
  { name: 'Ужгородська міська рада — розклад (GTFS)', city: 'Ужгород', providerType: 'public_transit', sourceType: 'gtfs', feedUrl: 'https://track.ua-gis.com/gtfs/uzhhorod/static.zip', access: 'open', updateFrequency: 'періодично', coverage: 'Міський транспорт Ужгорода', sourceRef: 'mdb:ua-uzhhorod-gtfs-2931', priority: 10 },
  { name: 'inbus.ua — розклад (GTFS)', city: 'Україна', providerType: 'public_transit', sourceType: 'gtfs', feedUrl: 'https://gtfs.fsn1.your-objectstorage.com/feeds/gtfs.zip', access: 'open', updateFrequency: 'періодично', coverage: 'Міжміські автобуси (inbus.ua), фід невеликий — потребує перевірки покриття', sourceRef: 'mdb:ua-inbusua-gtfs-3044', priority: 50 },
  { name: '3electra — е-самокати (GBFS 3.0)', city: 'Київ', providerType: 'scooter', sourceType: 'gbfs', feedUrl: 'https://zelectra.rideatom.com/gbfs/66/v3.0/gbfs', access: 'open', license: 'GBFS публічний фід оператора (умови уточнити у 3electra)', updateFrequency: 'майже реальний час', coverage: 'Е-самокати Києва, free-floating', sourceRef: 'gbfs-systems.csv:UA/3electra', priority: 10 },
  { name: 'Київ — розклад (GTFS)', city: 'Київ', providerType: 'public_transit', sourceType: 'gtfs', feedUrl: 'http://193.23.225.211:8002/export-gtfs-static', access: 'insecure_endpoint', license: 'CC BY 4.0', updateFrequency: 'періодично', coverage: 'Громадський транспорт Києва. Джерело доступне лише по http на IP-адресі, тому не підключається', sourceRef: 'mdb:ua-kyiv-gtfs-3230', priority: 10 },
  { name: 'Київ — realtime (GTFS-RT)', city: 'Київ', providerType: 'public_transit', sourceType: 'gtfs_rt', feedUrl: 'http://193.23.225.214:732/api/realtime', access: 'insecure_endpoint', license: 'CC BY 4.0', updateFrequency: 'реальний час', coverage: 'Realtime Києва. Лише http на IP-адресі, не підключається', sourceRef: 'mdb:ua-kiev-gtfs-rt-3231', priority: 10 },
  { name: 'Одеса — розклад (GTFS)', city: 'Одеса', providerType: 'public_transit', sourceType: 'gtfs', feedUrl: 'https://gw.x24.digital/api/od-all/gtfs/v1/download/static', access: 'requires_credentials', license: 'https://omr.gov.ua/ua/city/departments/dtks/open-data/', updateFrequency: 'періодично', coverage: 'Громадський транспорт Одеси. Потрібен ключ API (отримано HTTP 401)', sourceRef: 'mdb:ua-odesa-gtfs-2946', priority: 10 },
  { name: 'КП «Бучатранссервіс» — розклад (GTFS)', city: 'Буча', providerType: 'public_transit', sourceType: 'gtfs', feedUrl: 'https://gw.x24.digital/api/bu/gtfs/v1/download/static', access: 'requires_credentials', updateFrequency: 'періодично', coverage: 'Транспорт Бучі. Потрібен ключ API (отримано HTTP 401)', sourceRef: 'mdb:ua-bucha-gtfs-2945', priority: 10 },
];

const dozor = 'Платформа Dozor (city.dozor.tech); дані з відкритого порталу data.gov.ua';
const easyway = 'EasyWay (public.easyway.info); дані з відкритого порталу data.gov.ua';
/** Second wave (GitHub + data.gov.ua CKAN + platform probing, October 2026). */
export const ukraineCatalogWave2: CatalogEntry[] = [
  { name: 'Рівне — розклад (GTFS, Dozor)', city: 'Рівне', providerType: 'public_transit', sourceType: 'gtfs', feedUrl: 'https://city.dozor.tech/rivne/gtfs/static.zip', access: 'open', license: dozor, updateFrequency: 'періодично', coverage: 'Громадський транспорт Рівного', sourceRef: 'data.gov.ua:Рівненська міська рада', priority: 10 },
  { name: 'Рівне — позиції (GTFS-RT, Dozor)', city: 'Рівне', providerType: 'public_transit', sourceType: 'gtfs_rt', feedUrl: 'https://city.dozor.tech/rivne/gtfs/vehicle_position', access: 'open', license: dozor, updateFrequency: 'реальний час', coverage: 'Позиції транспорту Рівного', sourceRef: 'probe:city.dozor.tech', priority: 10 },
  { name: 'Івано-Франківськ — розклад (GTFS, Dozor)', city: 'Івано-Франківськ', providerType: 'public_transit', sourceType: 'gtfs', feedUrl: 'https://city.dozor.tech/iv-frankivsk/gtfs/static.zip', access: 'open', license: dozor, updateFrequency: 'періодично', coverage: 'Громадський транспорт Івано-Франківська', sourceRef: 'data.gov.ua:Управління транспорту Івано-Франківська', priority: 10 },
  { name: 'Івано-Франківськ — позиції (GTFS-RT, Dozor)', city: 'Івано-Франківськ', providerType: 'public_transit', sourceType: 'gtfs_rt', feedUrl: 'https://city.dozor.tech/iv-frankivsk/gtfs/vehicle_position', access: 'open', license: dozor, updateFrequency: 'реальний час', coverage: 'Позиції транспорту Івано-Франківська', sourceRef: 'data.gov.ua:Управління транспорту Івано-Франківська', priority: 10 },
  { name: 'Ужгород — позиції (GTFS-RT, Dozor)', city: 'Ужгород', providerType: 'public_transit', sourceType: 'gtfs_rt', feedUrl: 'https://city.dozor.tech/uzhgorod/gtfs/vehicle_position', access: 'open', license: dozor, updateFrequency: 'реальний час', coverage: 'Позиції транспорту Ужгорода', sourceRef: 'probe:city.dozor.tech', priority: 20 },
  { name: 'Ужгород — розклад (GTFS, Dozor)', city: 'Ужгород', providerType: 'public_transit', sourceType: 'gtfs', feedUrl: 'https://city.dozor.tech/uzhgorod/gtfs/static.zip', access: 'open', license: dozor, updateFrequency: 'періодично', coverage: 'Громадський транспорт Ужгорода (альтернативне джерело)', sourceRef: 'probe:city.dozor.tech', priority: 30 },
  { name: 'Стрий — позиції (GTFS-RT)', city: 'Стрий', providerType: 'public_transit', sourceType: 'gtfs_rt', feedUrl: 'https://track.ua-gis.com/gtfs/stryi/vehicle_position', access: 'open', updateFrequency: 'реальний час', coverage: 'Позиції транспорту Стрия', sourceRef: 'probe:track.ua-gis.com', priority: 10 },
  { name: 'Трускавець — позиції (GTFS-RT)', city: 'Трускавець', providerType: 'public_transit', sourceType: 'gtfs_rt', feedUrl: 'https://track.ua-gis.com/gtfs/truskavets/vehicle_position', access: 'open', updateFrequency: 'реальний час', coverage: 'Позиції транспорту Трускавця (фід може бути порожнім)', sourceRef: 'probe:track.ua-gis.com', priority: 10 },
  { name: 'Чорноморськ — розклад (GTFS)', city: 'Чорноморськ', providerType: 'public_transit', sourceType: 'gtfs', feedUrl: 'https://data.gov.ua/dataset/032c23f0-dbe5-4b63-8c1f-03218758ae60/resource/d997fdbf-7a25-487b-ad47-ee5541d552be/download/chornomorsk-2019-09-05-10-24-50.zip', access: 'open', license: 'data.gov.ua (відкриті дані); фід 2019 року', updateFrequency: 'не оновлюється (2019)', coverage: 'Громадський транспорт Чорноморська, застарілий', sourceRef: 'data.gov.ua:Виконавчий комітет Чорноморської міської ради', priority: 90 },
  { name: 'Червоноград — позиції (EasyWay JSON)', city: 'Червоноград', providerType: 'public_transit', sourceType: 'json', feedUrl: 'https://public.easyway.info/gps/chervonograd.json', access: 'open', license: easyway, updateFrequency: 'реальний час', coverage: 'Автобуси й маршрутки Червонограда', sourceRef: 'data.gov.ua:Шептицька міська рада', priority: 10 },
  { name: 'Конотоп — позиції (EasyWay JSON)', city: 'Конотоп', providerType: 'public_transit', sourceType: 'json', feedUrl: 'https://public.easyway.info/gps/konotop.json', access: 'open', license: easyway, updateFrequency: 'реальний час', coverage: 'Транспорт Конотопа', sourceRef: 'data.gov.ua:Управління економіки Конотопської міської ради', priority: 10 },
  { name: 'Ужгород — позиції (Dozor JSON)', city: 'Ужгород', providerType: 'public_transit', sourceType: 'json', feedUrl: 'https://city.dozor.tech/uzhgorod/devices.json', access: 'open', license: dozor, updateFrequency: 'реальний час', coverage: 'Позиції й типи транспорту Ужгорода', sourceRef: 'data.gov.ua:Ужгородська міська рада', priority: 40 },
  { name: 'Івано-Франківськ — позиції (Dozor JSON)', city: 'Івано-Франківськ', providerType: 'public_transit', sourceType: 'json', feedUrl: 'https://city.dozor.tech/iv-frankivsk/devices.json', access: 'open', license: dozor, updateFrequency: 'реальний час', coverage: 'Автобуси й тролейбуси Івано-Франківська', sourceRef: 'data.gov.ua:Управління транспорту Івано-Франківська', priority: 40 },
  { name: 'Дніпро — позиції (iCity JSON)', city: 'Дніпро', providerType: 'public_transit', sourceType: 'json', feedUrl: 'https://api-t900.icity.com.ua/api/gps_data/', access: 'open', license: 'відкриті дані Дніпровської міської ради (data.gov.ua)', updateFrequency: 'реальний час', coverage: 'Позиції транспорту Дніпра', sourceRef: 'data.gov.ua:Дніпровська міська рада', priority: 10 },
  { name: 'Суми — позиції (GTFS-RT)', city: 'Суми', providerType: 'public_transit', sourceType: 'gtfs_rt', feedUrl: 'http://gps.sumy.ua/gtfs/gtfs-vehicle-positions.proto', access: 'insecure_endpoint', license: 'data.gov.ua (Сумська міська рада)', updateFrequency: 'реальний час', coverage: 'Лише http, не підключається', sourceRef: 'data.gov.ua:Сумська міська рада', priority: 10 },
  { name: 'Полтава — позиції (EasyWay JSON)', city: 'Полтава', providerType: 'public_transit', sourceType: 'json', feedUrl: 'https://public.easyway.info/gps/poltava.json', access: 'open', license: easyway, updateFrequency: 'реальний час', coverage: 'Тролейбуси й маршрутки Полтави', sourceRef: 'probe:public.easyway.info', priority: 10 },
  { name: 'VD-Express — міжміські автобуси (GTFS)', city: 'Україна', providerType: 'public_transit', sourceType: 'gtfs', feedUrl: 'https://vdexpress.net/api/gtfs/feed', access: 'open', license: 'відкритий GTFS-фід перевізника (MobilityDatabase)', updateFrequency: 'щодня', coverage: 'Міжміські рейси VD-Express (Миколаїв, Новий Буг, Кривий Ріг тощо)', sourceRef: 'mobilitydatabase.org:VD-Express', priority: 30 },
  { name: 'Укрзалізниця — розклад поїздів (GTFS)', city: 'Україна', providerType: 'public_transit', sourceType: 'gtfs', feedUrl: 'https://jbb.ghsq.de/gtfs/ua-ukrzaliznytsya.gtfs.zip', access: 'open', license: 'ODbL (зібрано з OpenStreetMap, не офіційний фід УЗ)', updateFrequency: 'періодично', coverage: 'Далекі й регіональні поїзди по Україні', sourceRef: 'github.com/jqueguiner/gtfs (агрегатор GTFS-джерел)', priority: 40 },
  { name: 'Київпастранс — розклад (GTFS)', city: 'Київ', providerType: 'public_transit', sourceType: 'gtfs', feedUrl: 'https://jbb.ghsq.de/gtfs/ua-kyiv.gtfs.zip', access: 'open', license: 'CC BY 4.0 (дані КП «Київпастранс», https-дзеркало)', updateFrequency: 'щодня', coverage: 'Автобуси, тролейбуси й трамваї Києва', sourceRef: 'github.com/jqueguiner/gtfs (агрегатор GTFS-джерел)', priority: 20 },
  { name: 'Кам’янець-Подільський — розклад (GTFS, Dozor)', city: 'Кам’янець-Подільський', providerType: 'public_transit', sourceType: 'gtfs', feedUrl: 'https://city.dozor.tech/kamyanec/gtfs/static.zip', access: 'open', license: dozor, updateFrequency: 'щодня', coverage: 'Автобуси Кам’янця-Подільського', sourceRef: 'github.com/jqueguiner/gtfs (агрегатор GTFS-джерел)', priority: 40 },
  { name: 'Кам’янець-Подільський — позиції (Dozor JSON)', city: 'Кам’янець-Подільський', providerType: 'public_transit', sourceType: 'json', feedUrl: 'https://city.dozor.tech/kamyanec/devices.json', access: 'open', license: dozor, updateFrequency: 'реальний час', coverage: 'Позиції транспорту Кам’янця-Подільського', sourceRef: 'probe:city.dozor.tech', priority: 40 },
  { name: 'Біла Церква — розклад (GTFS, Dozor)', city: 'Біла Церква', providerType: 'public_transit', sourceType: 'gtfs', feedUrl: 'https://city.dozor.tech/bila-cerkva/gtfs/static.zip', access: 'open', license: dozor, updateFrequency: 'щодня', coverage: 'Автобуси Білої Церкви', sourceRef: 'github.com/jqueguiner/gtfs (агрегатор GTFS-джерел)', priority: 40 },
  { name: 'Біла Церква — позиції (Dozor JSON)', city: 'Біла Церква', providerType: 'public_transit', sourceType: 'json', feedUrl: 'https://city.dozor.tech/bila-cerkva/devices.json', access: 'open', license: dozor, updateFrequency: 'реальний час', coverage: 'Позиції транспорту Білої Церкви', sourceRef: 'probe:city.dozor.tech', priority: 40 },
  { name: 'Хмельницький — розклад (GTFS, Dozor)', city: 'Хмельницький', providerType: 'public_transit', sourceType: 'gtfs', feedUrl: 'https://city.dozor.tech/ua/khmelnyckyi/gtfs/static.zip', access: 'open', license: dozor, updateFrequency: 'щодня', coverage: 'Тролейбуси й автобуси Хмельницького', sourceRef: 'github.com/jqueguiner/gtfs (агрегатор GTFS-джерел)', priority: 40 },
  { name: 'Олександрія — розклад (GTFS, Dozor)', city: 'Олександрія', providerType: 'public_transit', sourceType: 'gtfs', feedUrl: 'https://city.dozor.tech/oleksandriya/gtfs/static.zip', access: 'open', license: dozor, updateFrequency: 'щодня', coverage: 'Автобуси Олександрії', sourceRef: 'github.com/jqueguiner/gtfs (агрегатор GTFS-джерел)', priority: 40 },
  { name: 'Олександрія — позиції (Dozor JSON)', city: 'Олександрія', providerType: 'public_transit', sourceType: 'json', feedUrl: 'https://city.dozor.tech/oleksandriya/devices.json', access: 'open', license: dozor, updateFrequency: 'реальний час', coverage: 'Позиції транспорту Олександрії', sourceRef: 'probe:city.dozor.tech', priority: 40 },
];
