ALTER TABLE journey_legs DROP CONSTRAINT IF EXISTS journey_legs_mode_check;
ALTER TABLE journey_legs ADD CONSTRAINT journey_legs_mode_check
  CHECK (mode IN ('WALK','COMMUNITY','COMMUNITY_DEMAND','TAXI','TRANSFER','BUS','MINIBUS','RAIL','TRAM','TROLLEYBUS','METRO','URBAN_BUS','CARSHARING','FERRY','FUNICULAR'));
